# Generated by Django 5.1.2 on 2024-12-03 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employermodule', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobdetails',
            name='job_type',
            field=models.CharField(choices=[('fulltime', 'Full-time'), ('contract', 'Contract'), ('parttime', 'Part-time')], max_length=20),
        ),
    ]
