# Generated by Django 5.1.2 on 2024-12-06 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employermodule', '0003_alter_jobdetails_job_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobdetails',
            name='job_type',
            field=models.CharField(choices=[('contract', 'Contract'), ('fulltime', 'Full-time'), ('parttime', 'Part-time')], max_length=20),
        ),
    ]
